/* This file is automatially generated by mkpat. Do not
edit it directly. Instead, edit the pattern database. */

struct patval {int x, y, att;};

struct pattern {
       struct patval *patn;
       int patlen;
       int trfno;
       int patwt;
};

struct patval con0[]={0,0,1,
   1,0,0,
   0,1,0,
   1,1,1};

struct patval con1[]={0,0,1,
   1,0,0,
   2,0,1,
   0,1,1,
   1,1,0,
   2,1,1};

struct patval con2[]={0,0,1,
   -1,1,4,
   0,1,4,
   1,1,1};

struct patval con3[]={0,0,1,
   1,0,0,
   2,0,0,
   0,1,1,
   1,1,0,
   2,1,1,
   1,2,0};

struct patval con4[]={-1,-1,0,
   -3,0,0,
   -2,0,0,
   -1,0,0,
   0,0,1,
   -3,1,1,
   -2,1,0,
   -1,1,1,
   0,1,0,
   -2,2,0};

struct patval con5[]={-1,0,0,
   0,0,1,
   1,0,0,
   2,0,0,
   -1,1,1,
   0,1,0,
   1,1,0,
   2,1,1,
   0,2,0,
   1,2,0,
   2,2,1};

struct patval con6[]={-1,0,0,
   0,0,1,
   1,0,0,
   2,0,0,
   -1,1,1,
   0,1,0,
   1,1,0,
   2,1,1,
   -1,2,1,
   0,2,0,
   1,2,0,
   2,2,0};

struct patval con7[]={0,0,1,
   1,0,1,
   2,0,0,
   3,0,0,
   0,1,1,
   1,1,0,
   2,1,0,
   3,1,1,
   0,2,1,
   1,2,0,
   2,2,0,
   3,2,0};

struct patval con8[]={0,0,1,
   1,0,1,
   -1,1,1,
   0,1,0,
   1,1,1,
   -1,2,1,
   0,2,1};

struct patval con9[]={0,0,1,
   -1,1,1,
   0,1,0,
   1,1,1,
   0,2,0};

static struct pattern con[]=
{con0,4,2,4,
 con1,6,4,4,
 con2,4,8,1,
 con3,7,8,2,
 con4,10,8,2,
 con5,11,8,3,
 con6,12,8,3,
 con7,12,8,3,
 con8,7,4,3,
 con9,5,4,3};

#define CONNO 10

