/* Compile the pattern database. This produces patterns.h. */
/* Copyright 1998 by Daniel Bump */

#define MAXLINE 120
#define MAXPATNO 1000

#include <stdio.h>

main(int *argc,char *argv[])
{
  char line[MAXLINE];
  int i[360],j[360],ci=-1,cj=-1,nexti=0,nextj=0,node;
  int code[360];
  int patno=0,maxpat;
  int patlen[MAXPATNO],trfno[MAXPATNO],patwt[MAXPATNO];
  
  printf(
"/* This file is automatially generated by mkpat. Do not
edit it directly. Instead, edit the pattern database. */

struct patval {int x, y, att;};\n
struct pattern {
       struct patval *patn;
       int patlen;
       int trfno;
       int patwt;
};\n\n");

  patno=0;
  patlen[patno]=0;
  while (fgets(line,MAXLINE,stdin)) {
    if (line[0]!='#') {
      if ((line[0]=='0')||(line[0]=='1')||(line[0]=='2')||(line[0]=='3')||(line[0]=='4')||(line[0]=='5')||(line[0]=='6')||(line[0]=='7')||(line[0]=='8')||(line[0]=='9')||(line[0]=='k')||(line[0]=='m')||(line[0]=='*')) {
	for (nextj=0;((line[nextj]=='0')||(line[nextj]=='1')||(line[nextj]=='2')||(line[nextj]=='3')||(line[nextj]=='4')||(line[nextj]=='5')||(line[nextj]=='6')||(line[nextj]=='7')||(line[nextj]=='8')||(line[nextj]=='9')||(line[nextj]=='k')||(line[nextj]=='m')||(line[nextj]=='*'));nextj++) {
	  if (line[nextj]!='*') {
	    i[patlen[patno]]=nexti;
	    j[patlen[patno]]=nextj;
	    if ((ci==-1)&&((line[nextj]=='2')||(line[nextj]=='6')||
			(line[nextj]=='1')||(line[nextj]=='5'))||(line[nextj]=='8')||(line[nextj]=='9')) {
	      ci=nexti;
	      cj=nextj;
	    }
	    if (line[nextj]=='k') {
	      code[patlen[patno]]=10;
	    } else if (line[nextj]=='m') {
	      code[patlen[patno]]=11;
	    } else code[patlen[patno]]=line[nextj]-'0';
	    patlen[patno]++;
	  }
	}
	nexti++;
      }
      if (line[0]==':') {
	printf("struct patval %s%d[]={",argv[1],patno);
	for (node=0;node<patlen[patno]-1;node++) {
	  printf("%d,%d,%d,\n   ",j[node]-cj,i[node]-ci,code[node]);
	}
	printf("%d,%d,%d};\n\n",j[patlen[patno]-1]-cj,i[patlen[patno]-1]-ci,code[patlen[patno]-1]);
	sscanf(line,":%d,%d",&trfno[patno],&patwt[patno]); 
	patno++;
	patlen[patno]=0;
	nexti=0;
	ci=cj=-1;
      }
    }
  }
  maxpat=patno;
  printf("static struct pattern %s[]=\n{",argv[1]);
  for(patno=0;patno<maxpat-1;patno++) {
    printf("%s%d,%d,%d,%d,\n ",argv[1],patno,patlen[patno],trfno[patno],patwt[patno]);
  }
  printf("%s%d,%d,%d,%d};\n\n",argv[1],patno,patlen[maxpat-1],trfno[maxpat-1],patwt[maxpat-1]);
  argv[1][0]=toupper(argv[1][0]);
  argv[1][1]=toupper(argv[1][1]);
  argv[1][2]=toupper(argv[1][2]);
  printf("#define %sNO %d\n\n",argv[1],maxpat);
  return(0);
}







